INSERT into student (FIRST_NAME,LAST_NAME,TELEPHONE,DEGREE_PROGRAM,PARENTS_CONTACT,STUDENT_ID,ImageURL)
VALUES ('Riya','Bajaj','+95621846','BSCS','+928761561','0532-6156-251','/plugins/images/users/d2.jpg');
INSERT into student (FIRST_NAME,LAST_NAME,TELEPHONE,DEGREE_PROGRAM,PARENTS_CONTACT,STUDENT_ID,ImageURL )
VALUES ('Rubab','Khalid','+9561216','BSSE','+925181561','0532-6156-741','/plugins/images/users/d1.jpg');
INSERT into student (FIRST_NAME,LAST_NAME,TELEPHONE,DEGREE_PROGRAM,PARENTS_CONTACT,STUDENT_ID,ImageURL)
VALUES ('Mohammad','Saeed','+95609846','BBA','+92598061','0532-6156-111','/plugins/images/users/d2.jpg');
INSERT into student (FIRST_NAME,LAST_NAME,TELEPHONE,DEGREE_PROGRAM,PARENTS_CONTACT,STUDENT_ID,ImageURL)
VALUES ('Mohammad','Waqar','+95652846','MBA','+921435561','0532-6156-023','/plugins/images/users/d3.jpg');
INSERT into student (FIRST_NAME,LAST_NAME,TELEPHONE,DEGREE_PROGRAM,PARENTS_CONTACT,STUDENT_ID,ImageURL)
VALUES ('M','Ali','+95625646','BE','+925181561','0598-6156-251','/plugins/images/users/p.jpg');

INSERT into room (FLOOR, ROOM_NUMBER, CAPACITY, VACCANCY) VALUES ('Ground','1','3','3');
INSERT into room (FLOOR, ROOM_NUMBER, CAPACITY, VACCANCY) VALUES ('Ground','2','4','4');
INSERT into room (FLOOR, ROOM_NUMBER, CAPACITY, VACCANCY) VALUES ('Ground','3','2','2');
INSERT into room (FLOOR, ROOM_NUMBER, CAPACITY, VACCANCY) VALUES ('First','101','2','2');
INSERT into room (FLOOR, ROOM_NUMBER, CAPACITY, VACCANCY) VALUES ('First','102','3','3');
INSERT into room (FLOOR, ROOM_NUMBER, CAPACITY, VACCANCY) VALUES ('First','103','3','3');
INSERT into room (FLOOR, ROOM_NUMBER, CAPACITY, VACCANCY) VALUES ('Second','201','2','2');
INSERT into room (FLOOR, ROOM_NUMBER, CAPACITY, VACCANCY) VALUES ('Second','202','2','2');
INSERT into room (FLOOR, ROOM_NUMBER, CAPACITY, VACCANCY) VALUES ('Second','203','1','1');

INSERT into warden (FIRST_NAME,LAST_NAME,TELEPHONE) VALUES ('Alex','Bhatti','+95180515');
INSERT into warden (FIRST_NAME,LAST_NAME,TELEPHONE) VALUES ('George','Woods','+9518741');
INSERT into warden (FIRST_NAME,LAST_NAME,TELEPHONE) VALUES ('Hamza','Zain','+957455');
INSERT into warden (FIRST_NAME,LAST_NAME,TELEPHONE) VALUES ('Khalid','Waseem','+959855');

INSERT into complain(MESSAGE,STUDENT_ID,COMPLAIN_TYPE,COMPLAIN_STATUS) VALUES ('Complain about new side table','1','INDIVIDUAL','PENDING');

INSERT into complain(MESSAGE,STUDENT_ID,COMPLAIN_TYPE,COMPLAIN_STATUS) VALUES ('Change Mess Manager','2','GENERAL','APPROVED');

INSERT into complain(MESSAGE,STUDENT_ID,COMPLAIN_TYPE,COMPLAIN_STATUS) VALUES ('Complain about new side table','3','GENERAL','REJECTED');
